from lang import lang_de, lang_fr, lang_ca, lang_es, lang_ru, lang_en, lang_tr, lang_pl, lang_it, lang_nl, lang_nb, lang_ko, lang_vi, lang_el, lang_zh_TW
from lang import lang_zh_CN, lang_pt, lang_ja, lang_fi, lang_id, lang_sr, lang_lt, lang_sv, lang_ua, lang_da, lang_lv, lang_hu, lang_sk

lang = None

languages = {
    "ca": lang_ca,
    "da": lang_da,
    "de": lang_de,
    "el": lang_el,
    "en": lang_en,
    "es": lang_es,
    "fi": lang_fi,
    "fr": lang_fr,
    "hu": lang_hu,
    "id": lang_id,
    "it": lang_it,
    "ja": lang_ja,
    "ko": lang_ko,
    "lt": lang_lt,
    "lv": lang_lv,
    "nb": lang_nb,
    "nl": lang_nl,
    "pl": lang_pl,
    "pt": lang_pt,
    "ru": lang_ru,
    "sr": lang_sr,
    "sv": lang_sv,
    "tr": lang_tr,
    "ua": lang_ua,
    "vi": lang_vi,
    "zh_TW": lang_zh_TW,
    "zh_CN": lang_zh_CN,
}

languageReference = {
    "default": "System language",
    "ca": "Catalan",
    "da": "Danish",
    "nl": "Dutch"  ,
    "en": "English",
    "fi": "Finnish",
    "fr": "French" ,
    "de": "German" ,
    "el": "Greek"  ,
    "hu": "Hungarian",
    "id": "Indonesian",
    "it": "Italian",
    "ja": "Japanese",
    "ko": "Korean ",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "nb": "Norwegian",
    "pl": "Polish" ,
    "pt": "Portuguese",
    "ru": "Russian",
    "zh_CN": "Simplified Chinese (China)",
    "sr": "Serbian",
    "es": "Spanish",
    "sv": "Swedish",
    "zh_TW": "Traditional Chinese (Taiwan)",
    "tr": "Turkish",
    "ua": "Ukranian",
    "vi": "Vietnamese",
}