lang = {}

languages = {
    "ar":    "lang_ar.json",
    "ca":    "lang_ca.json",
    "cs":    "lang_cs.json",    
    "da":    "lang_da.json",
    "de":    "lang_de.json",
    "el":    "lang_el.json",
    "en":    "lang_en.json",
    "es":    "lang_es.json",
    "fi":    "lang_fi.json",
    "he":    "lang_he.json",
    "fr":    "lang_fr.json",
    "hu":    "lang_hu.json",
    "id":    "lang_id.json",
    "it":    "lang_it.json",
    "ja":    "lang_ja.json",
    "ko":    "lang_ko.json",
    "lt":    "lang_lt.json",
    "lv":    "lang_lv.json",
    "nb":    "lang_nb.json",
    "nl":    "lang_nl.json",
    "nn":    "lang_nn.json",
    "pl":    "lang_pl.json",
    "pt_PT": "lang_pt_PT.json",
    "pt_BR": "lang_pt_BR.json",
    "ru":    "lang_ru.json",
    "sk":    "lang_sk.json",
    "sr":    "lang_sr.json",
    "sv":    "lang_sv.json",
    "th":    "lang_th.json",
    "tr":    "lang_tr.json",
    "ua":    "lang_ua.json",
    "vi":    "lang_vi.json",
    "zh_TW": "lang_zh_TW.json",
    "zh_CN": "lang_zh_CN.json",
}

languageReference = {
    "default": "System language",
    "ar"    : "Arabic",
    "ca"    : "Catalan",
    "cs"    : "Czech",
    "da"    : "Danish",
    "nl"    : "Dutch"  ,
    "en"    : "English",
    "fi"    : "Finnish",
    "fr"    : "French" ,
    "de"    : "German" ,
    "el"    : "Greek"  ,
    "he"    : "Hebrew",
    "hu"    : "Hungarian",
    "id"    : "Indonesian",
    "it"    : "Italian",
    "ja"    : "Japanese",
    "ko"    : "Korean ",
    "lv"    : "Latvian",
    "lt"    : "Lithuanian",
    "nb"    : "Norwegian (bokmål)",
    "nn"    : "Norwegian (nynorsk)",
    "pl"    : "Polish",
    "pt_PT" : "Portuguese (Portugal)",
    "pt_BR" : "Portuguese (Brazil)",
    "ru"    : "Russian",
    "zh_CN" : "Simplified Chinese (China)",
    "sr"    : "Serbian",
    "sk"    : "Slovak",
    "es"    : "Spanish",
    "sv"    : "Swedish",
    "th"    : "Thai",
    "zh_TW" : "Traditional Chinese (Taiwan)",
    "tr"    : "Turkish",
    "ua"    : "Ukranian",
    "vi"    : "Vietnamese",
}

debugLang = False

