import sys
import json
import os

sys.path.append('../');
from languages import languageReference


try:
    apikey = open("APIKEY.txt", "r").read()
    print("  API key found in APIKEY.txt")
except FileNotFoundError:
    apikey = input("Write api key and press enter: ")

apiurl = f"https://app.tolgee.io/v2/projects/688/export?format=JSON&splitByScope=false&splitByScopeDelimiter=~&splitByScopeDepth=0&filterState=UNTRANSLATED&filterState=TRANSLATED&filterState=REVIEWED&zip=true&ak={apikey}"

import os
try:
    import requests
except ImportError:
    os.system("pip install requests")
    import requests
import glob, time, shutil, zipfile


print()
print("-------------------------------------------------------")
print()
print("  Downloading updated translations...")

zipcontent = requests.get(apiurl)
open("langs.zip", "wb").write(zipcontent.content)

print("  Download complete!")
print()
print("-------------------------------------------------------")
print()
print("  Extracting language files...")


languageRemap = {
    "pt-PT":      "pt_PT",
    "pt-BR":      "pt_BR",
    "uk":         "ua",
    "zh-Hant-TW": "zh_TW",
    "zh-Hans-CN": "zh_CN",
}
downloadedLanguages = []


#olddir = "lang_backup"+str(int(time.time()))
#os.mkdir(olddir)
for file in glob.glob('lang_*.json'):
    os.remove(file)
#    shutil.move(file, olddir)

#print(f"  Backup complete. The old files were moved to {olddir}")
#print()
print("-------------------------------------------------------")
print()
print("  Extracting language files...")


zip_file = zipfile.ZipFile("langs.zip")
for name in zip_file.namelist():
    lang = os.path.splitext(name)[0]
    if (lang in languageRemap):
        lang = languageRemap[lang]
    newFilename = f"lang_{lang}.json"
    downloadedLanguages.append(lang)

    try:
        zip_file.extract(name, "./")
        os.replace(name, newFilename)

        print(f"  Extracted {newFilename}")
    except KeyError as e:
        print(type(name))
        f = input(f"  The file {name} was not expected to be in here. Please write the name for the file. It should follow the following structure: lang_[CODE].json: ")
        zip_file.extract(f, "./")
        os.replace(f, newFilename)
        print(f"  Extracted {f}")
zip_file.close()
downloadedLanguages.sort()
os.remove("langs.zip")


print("  Process complete!")
print()
print("-------------------------------------------------------")
print()
print("  Generating translation done file...")


langPerc = {}
for lang in downloadedLanguages:
    f = open(f"lang_{lang}.json", "r", encoding='utf-8')
    data = json.load(f)
    f.close()
    c = 0
    a = 0
    for key, value in data.items():
        c += 1
        if (value != None):
            a += 1
    perc = "{:.0%}".format(a / c)
    if (perc == "100%" or lang == "en"):
        continue
    langPerc[lang] = perc

outputString = f"""
# Autogenerated file, do not modify it!!!
# The following list includes ONLY non-full translated files.

untranslatedPercentage = {json.dumps(langPerc, indent=2)}
"""

f = open(f"translated_percentage.py", "w")
f.write(outputString.strip())
f.close()


print("  Process complete!")
print()
print("-------------------------------------------------------")
print()
print("  Updating README.md...")


# ISO 3166-1
languageFlagsRemap = {
    "ca": "ad",
    "cs": "cz",
    "da": "dk",
    "en": "gb",
    "el": "gr",
    "he": "il",
    "ja": "jp",
    "ko": "kr",
    "nb": "no",
    "nn": "no",
    "pt_BR": "br",
    "pt_PT": "pt",
    "si": "lk",
    "zh_CN": "cn",
    "zh_TW": "tw",
}
readmeFilename = "../../README.md"
readmeLangs = """
| Language | Translated | |
| :-- | :-- | --- |
"""

for lang in downloadedLanguages:
    perc = "100%"
    langName = lang
    flag = lang
    if (lang in langPerc): perc = langPerc[lang]
    if (lang in languageReference): langName = languageReference[lang]
    if (lang in languageFlagsRemap): flag = languageFlagsRemap[lang]
    readmeLangs += f"| {langName} | {perc} | <img src='https://flagcdn.com/{flag}.svg' width=20> |\n"

f = open(readmeFilename, "r+", encoding="utf-8")
skip = False
data = ""
for line in f.readlines():
    if (line.startswith("<!-- Autogenerated translations -->")):
        data += line + readmeLangs
        print("  Text modified")
        skip = True
    if (line.startswith("<!-- END Autogenerated translations -->")):
        skip = False
    if (not skip): data += line
f.seek(0)
f.write(data)
f.close()


print("  Process complete!")
print()
print("-------------------------------------------------------")
print()
os.system("pause")
