# Autogenerated file, do not modify it!!!
# The following list includes ONLY non-full translated files.

untranslatedPercentage = {
  "ar": "67%",
  "da": "26%",
  "el": "20%",
  "fi": "68%",
  "it": "52%",
  "lt": "24%",
  "lv": "66%",
  "nl": "87%",
  "nn": "73%",
  "pt_BR": "85%",
  "sk": "32%",
  "sr": "24%",
  "sv": "80%",
  "th": "87%",
  "tr": "21%",
  "ua": "26%",
  "vi": "42%",
  "zh_TW": "83%"
}