# Autogenerated file, do not modify it!!!
# The following list includes ONLY non-full translated files.

untranslatedPercentage = {
  "ar": "67%",
  "da": "26%",
  "de": "98%",
  "el": "20%",
  "fi": "58%",
  "he": "29%",
  "hu": "66%",
  "id": "21%",
  "it": "52%",
  "lt": "24%",
  "lv": "35%",
  "nb": "98%",
  "nl": "53%",
  "nn": "73%",
  "pt_BR": "74%",
  "pt_PT": "29%",
  "ro": "40%",
  "ru": "80%",
  "si": "0%",
  "sk": "33%",
  "sr": "24%",
  "sv": "80%",
  "th": "80%",
  "tr": "21%",
  "ua": "26%",
  "vi": "18%",
  "zh_CN": "73%",
  "zh_TW": "84%"
}