# Autogenerated file, do not modify it!!!
# The following list includes ONLY non-full translated files.

untranslatedPercentage = {
  "ar": "65%",
  "bg": "17%",
  "bs": "6%",
  "da": "99%",
  "de": "96%",
  "el": "18%",
  "es": "99%",
  "et": "88%",
  "fa": "5%",
  "he": "88%",
  "hr": "10%",
  "hu": "95%",
  "id": "88%",
  "it": "97%",
  "ja": "96%",
  "lt": "19%",
  "lv": "58%",
  "nl": "87%",
  "pl": "93%",
  "ro": "88%",
  "ru": "99%",
  "sk": "30%",
  "sr": "19%",
  "sv": "73%",
  "th": "77%",
  "ua": "95%",
  "vi": "96%",
  "zh_CN": "99%"
}