# Autogenerated file, do not modify it!!!

contributors = [
  "marticliment",
  "panther7",
  "kirill-d-lappo",
  "Lilobast",
  "BoyceLig",
  "sinusinu",
  "Seeloewen",
  "VenusGirl",
  "noname-ctrl",
  "ShintakuNobuhiro",
  "xsm1997",
  "wanderleihuttel",
  "mmis1000",
  "norway-yv",
  "jameshamm",
  "jmlcoliveira",
  "richeyphu",
  "viktak",
  "MatousAdamu",
  "SkebbZ",
  "scrocquesel",
  "domlobo",
  "harel013",
  "kinr0k",
  "ppvnf",
  "jstmrby"
]

contributorsInfo = [
  {
    "name": "marticliment",
    "link": "https://github.com/marticliment",
    "contributions": 1721
  },
  {
    "name": "panther7",
    "link": "https://github.com/panther7",
    "contributions": 87
  },
  {
    "name": "kirill-d-lappo",
    "link": "https://github.com/kirill-d-lappo",
    "contributions": 32
  },
  {
    "name": "Lilobast",
    "link": "https://github.com/Lilobast",
    "contributions": 25
  },
  {
    "name": "BoyceLig",
    "link": "https://github.com/BoyceLig",
    "contributions": 20
  },
  {
    "name": "sinusinu",
    "link": "https://github.com/sinusinu",
    "contributions": 15
  },
  {
    "name": "Seeloewen",
    "link": "https://github.com/Seeloewen",
    "contributions": 13
  },
  {
    "name": "VenusGirl",
    "link": "https://github.com/VenusGirl",
    "contributions": 13
  },
  {
    "name": "noname-ctrl",
    "link": "https://github.com/noname-ctrl",
    "contributions": 11
  },
  {
    "name": "ShintakuNobuhiro",
    "link": "https://github.com/ShintakuNobuhiro",
    "contributions": 10
  },
  {
    "name": "xsm1997",
    "link": "https://github.com/xsm1997",
    "contributions": 9
  },
  {
    "name": "wanderleihuttel",
    "link": "https://github.com/wanderleihuttel",
    "contributions": 8
  },
  {
    "name": "mmis1000",
    "link": "https://github.com/mmis1000",
    "contributions": 8
  },
  {
    "name": "norway-yv",
    "link": "https://github.com/norway-yv",
    "contributions": 8
  },
  {
    "name": "jameshamm",
    "link": "https://github.com/jameshamm",
    "contributions": 6
  },
  {
    "name": "jmlcoliveira",
    "link": "https://github.com/jmlcoliveira",
    "contributions": 6
  },
  {
    "name": "richeyphu",
    "link": "https://github.com/richeyphu",
    "contributions": 4
  },
  {
    "name": "viktak",
    "link": "https://github.com/viktak",
    "contributions": 4
  },
  {
    "name": "MatousAdamu",
    "link": "https://github.com/MatousAdamu",
    "contributions": 3
  },
  {
    "name": "SkebbZ",
    "link": "https://github.com/SkebbZ",
    "contributions": 3
  },
  {
    "name": "scrocquesel",
    "link": "https://github.com/scrocquesel",
    "contributions": 3
  },
  {
    "name": "domlobo",
    "link": "https://github.com/domlobo",
    "contributions": 3
  },
  {
    "name": "harel013",
    "link": "https://github.com/harel013",
    "contributions": 3
  },
  {
    "name": "kinr0k",
    "link": "https://github.com/kinr0k",
    "contributions": 3
  },
  {
    "name": "ppvnf",
    "link": "https://github.com/ppvnf",
    "contributions": 3
  },
  {
    "name": "jstmrby",
    "link": "https://github.com/jstmrby",
    "contributions": 3
  }
]