# Autogenerated file, do not modify it!!!

untranslatedPercentage = {
  "ar": "69%",
  "bg": "16%",
  "bs": "5%",
  "cs": "98%",
  "el": "17%",
  "es": "97%",
  "et": "83%",
  "eu": "84%",
  "fa": "5%",
  "fi": "95%",
  "he": "83%",
  "hr": "79%",
  "hu": "90%",
  "id": "83%",
  "it": "97%",
  "ja": "91%",
  "lt": "19%",
  "lv": "55%",
  "nl": "86%",
  "ro": "83%",
  "sk": "28%",
  "sr": "19%",
  "sv": "69%",
  "th": "73%",
  "ua": "90%"
}

languageCredits = {
  "ar": [],
  "bg": [],
  "bs": [],
  "ca": [
    {
      "name": "marticliment",
      "link": "https://github.com/marticliment"
    }
  ],
  "cs": [
    {
      "name": "MatousAdamu",
      "link": "https://github.com/MatousAdamu"
    },
    {
      "name": "panther7",
      "link": "https://github.com/panther7"
    },
    {
      "name": "SunightMC",
      "link": "https://github.com/SunightMC"
    }
  ],
  "da": [
    {
      "name": "Carsten Kristoffersen",
      "link": ""
    },
    {
      "name": "Sebblich",
      "link": ""
    }
  ],
  "de": [
    {
      "name": "Bikholf",
      "link": ""
    },
    {
      "name": "Seeloewen",
      "link": "https://github.com/Seeloewen"
    },
    {
      "name": "tsloms",
      "link": "https://github.com/tsloms"
    },
    {
      "name": "XenoKeks",
      "link": "https://github.com/XenoKeks"
    }
  ],
  "el": [
    {
      "name": "panos78",
      "link": "https://github.com/panos78"
    }
  ],
  "en": [
    {
      "name": "marticliment",
      "link": "https://github.com/marticliment"
    }
  ],
  "es": [
    {
      "name": "marticliment",
      "link": "https://github.com/marticliment"
    }
  ],
  "et": [],
  "eu": [
    {
      "name": "Alexandre",
      "link": ""
    }
  ],
  "fa": [],
  "fi": [
    {
      "name": "npsand",
      "link": "https://github.com/npsand"
    }
  ],
  "fr": [
    {
      "name": "Lilobast",
      "link": "https://github.com/Lilobast"
    },
    {
      "name": "scrocquesel",
      "link": "https://github.com/scrocquesel"
    }
  ],
  "he": [
    {
      "name": "xRLx",
      "link": ""
    }
  ],
  "hr": [
    {
      "name": "DMNz3",
      "link": "https://github.com/DMNz3"
    }
  ],
  "hu": [
    {
      "name": "gidano",
      "link": "https://github.com/gidano"
    },
    {
      "name": "jstmrby",
      "link": "https://github.com/jstmrby"
    },
    {
      "name": "sympda.blog.hu",
      "link": ""
    },
    {
      "name": "viktak.com",
      "link": ""
    }
  ],
  "id": [
    {
      "name": "adinugrahasatya",
      "link": "https://github.com/adinugrahasatya"
    },
    {
      "name": "FahrulID",
      "link": ""
    }
  ],
  "it": [
    {
      "name": "Parapongo",
      "link": "https://github.com/Parapongo"
    },
    {
      "name": "zuidstroopwafel",
      "link": "https://github.com/zuidstroopwafel"
    }
  ],
  "ja": [
    {
      "name": "Robot-Inventor",
      "link": "https://github.com/Robot-Inventor"
    },
    {
      "name": "ShintakuNobuhiro",
      "link": "https://github.com/ShintakuNobuhiro"
    }
  ],
  "ko": [
    {
      "name": "sinusinu",
      "link": "https://github.com/sinusinu"
    },
    {
      "name": "VenusGirl",
      "link": "https://github.com/VenusGirl"
    }
  ],
  "lt": [
    {
      "name": "generic pleb",
      "link": ""
    }
  ],
  "lv": [
    {
      "name": "dejelnieks",
      "link": "https://github.com/dejelnieks"
    },
    {
      "name": "shadow118",
      "link": "https://github.com/shadow118"
    }
  ],
  "nb": [
    {
      "name": "norway-yv",
      "link": ""
    }
  ],
  "nl": [
    {
      "name": "Bugs",
      "link": ""
    },
    {
      "name": "joosthoi1",
      "link": "https://github.com/joosthoi1"
    },
    {
      "name": "jordyegnl",
      "link": "https://github.com/jordyegnl"
    }
  ],
  "nn": [
    {
      "name": "norway-yv",
      "link": ""
    }
  ],
  "pl": [
    {
      "name": "PabloMat",
      "link": "https://github.com/PabloMat"
    }
  ],
  "pt_BR": [
    {
      "name": "gumbarros",
      "link": "https://github.com/gumbarros"
    },
    {
      "name": "maisondasilva",
      "link": "https://github.com/maisondasilva"
    },
    {
      "name": "wanderleihuttel",
      "link": "https://github.com/wanderleihuttel"
    }
  ],
  "pt_PT": [
    {
      "name": "jmlcoliveira",
      "link": "https://github.com/jmlcoliveira"
    },
    {
      "name": "Miguel Couto",
      "link": ""
    }
  ],
  "ro": [],
  "ru": [
    {
      "name": "kira-lappo",
      "link": "https://github.com/kira-lappo"
    },
    {
      "name": "Risen",
      "link": ""
    }
  ],
  "sk": [
    {
      "name": "metmanik",
      "link": "https://github.com/metmanik"
    }
  ],
  "sl": [
    {
      "name": "rumplin",
      "link": "https://github.com/rumplin"
    }
  ],
  "sr": [
    {
      "name": "Stefan Marjanov",
      "link": ""
    }
  ],
  "sv": [
    {
      "name": "cjal95",
      "link": "https://github.com/cjal95"
    },
    {
      "name": "Noffe",
      "link": ""
    }
  ],
  "th": [
    {
      "name": "richeyphu",
      "link": "https://github.com/richeyphu"
    }
  ],
  "tr": [
    {
      "name": "Mahmut Sözen",
      "link": ""
    }
  ],
  "ua": [
    {
      "name": "p4rzivalll",
      "link": "https://github.com/p4rzivalll"
    }
  ],
  "vi": [
    {
      "name": "legendsjoon",
      "link": "https://github.com/legendsjoon"
    },
    {
      "name": "Leoodz",
      "link": "https://github.com/Leoodz"
    },
    {
      "name": "lequan81",
      "link": "https://github.com/lequan81"
    },
    {
      "name": "Quochieu0211",
      "link": "https://github.com/Quochieu0211"
    },
    {
      "name": "tnhung2011",
      "link": "https://github.com/tnhung2011"
    }
  ],
  "zh_CN": [
    {
      "name": "BoyceLig",
      "link": "https://github.com/BoyceLig"
    },
    {
      "name": "CnYeSheng",
      "link": ""
    },
    {
      "name": "hlgsdx",
      "link": "https://github.com/hlgsdx"
    },
    {
      "name": "jmlcoliveira",
      "link": "https://github.com/jmlcoliveira"
    },
    {
      "name": "strombooli",
      "link": "https://github.com/strombooli"
    }
  ],
  "zh_TW": [
    {
      "name": "BoyceLig",
      "link": "https://github.com/BoyceLig"
    },
    {
      "name": "CnYeSheng",
      "link": ""
    },
    {
      "name": "mmis1000",
      "link": "https://github.com/mmis1000"
    },
    {
      "name": "SiderealArt",
      "link": "https://github.com/SiderealArt"
    }
  ]
}